### PR TITLE
Add new page copy

### PR DESCRIPTION
**Pull request by brdlyptrs**

### CODE REVIEW

**Comment by e271828-** [comment]
This script does not preserve the order on page of translations. Please do not use/translate as is.

**Comment by wontem** [comment]
@e271828- you mean `get_copy.js` script?

**Comment by e271828-** [comment]
> @e271828- you mean `get_copy.js` script?

Yes. Compare the output vs. what it's replacing: you can read the old one straight through.

**Comment by wontem** [comment]
@e271828- @brdlyptrs here is the cursed version of custom parser/stringyfier (I made a new branch based on the current one). The problem is that JSON dictionary is unordered by spec

https://github.com/hCaptcha/website-i18n/pull/34/files

Read JSON
https://github.com/hCaptcha/website-i18n/pull/34/commits/0f61f40faa28ee04db2233785318de13e3a63c78#diff-6b6f1ae977bad6eb99dda938cb048920980a3868ba34e7e3c589643f4c4b073bR14-R18

Write JSON
https://github.com/hCaptcha/website-i18n/pull/34/commits/0f61f40faa28ee04db2233785318de13e3a63c78#diff-6b6f1ae977bad6eb99dda938cb048920980a3868ba34e7e3c589643f4c4b073bR55-R61

**Pull request closed without merging**
